-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 21:30:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema technical_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema technical_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `technical_test` DEFAULT CHARACTER SET utf8 ;
USE `technical_test` ;

-- -----------------------------------------------------
-- Table `technical_test`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technical_test`.`User` (
  `cedula` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `creado` DATETIME NOT NULL,
  `actualizado` DATETIME NOT NULL,
  `rol` ENUM("ADMIN", "CLIENTE") NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technical_test`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technical_test`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  `imagen` TEXT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `creado` DATETIME NOT NULL,
  `actualizado` DATETIME NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technical_test`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technical_test`.`carrito` (
  `idcarrito` INT NOT NULL,
  `User_cedula` INT NOT NULL,
  `creado` DATETIME NOT NULL,
  `actualizado` DATETIME NOT NULL,
  PRIMARY KEY (`idcarrito`, `User_cedula`),
  INDEX `fk_carrito_User_idx` (`User_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_User`
    FOREIGN KEY (`User_cedula`)
    REFERENCES `technical_test`.`User` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technical_test`.`productos_en_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technical_test`.`productos_en_carrito` (
  `carrito_idcarrito` INT NOT NULL,
  `carrito_User_cedula` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`carrito_idcarrito`, `carrito_User_cedula`, `Producto_idProducto`),
  INDEX `fk_carrito_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_carrito_has_Producto_carrito1_idx` (`carrito_idcarrito` ASC, `carrito_User_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_has_Producto_carrito1`
    FOREIGN KEY (`carrito_idcarrito` , `carrito_User_cedula`)
    REFERENCES `technical_test`.`carrito` (`idcarrito` , `User_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `technical_test`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `technical_test`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `technical_test`.`orden` (
  `idorden` INT NOT NULL,
  `carrito_idcarrito` INT NOT NULL,
  `carrito_User_cedula` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `estado` ENUM("pendiente", "pagada", "cancelada") NOT NULL,
  `total` FLOAT NOT NULL,
  PRIMARY KEY (`idorden`, `carrito_idcarrito`, `carrito_User_cedula`),
  INDEX `fk_orden_carrito1_idx` (`carrito_idcarrito` ASC, `carrito_User_cedula` ASC) VISIBLE,
  CONSTRAINT `fk_orden_carrito1`
    FOREIGN KEY (`carrito_idcarrito` , `carrito_User_cedula`)
    REFERENCES `technical_test`.`carrito` (`idcarrito` , `User_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
